name: Publish to S3 bucket
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to checkout'
        required: true
        type: string
  push:
    tags:
      - 'v*'  # Matches any tag starting with 'v'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    # Method 1: Checkout specific tag using ref
      - name: Checkout specific tag
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.tag || github.ref }}  # Uses input tag or the pushed tag
          fetch-depth: 0
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: resume.tex
      - name: Rename resume file
        run: mv resume.pdf eftakhairul_islam_resume.pdf

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}  # I didn't want expose the region
      - name: Upload to S3
        run: |
          aws s3 cp ./eftakhairul_islam_resume.pdf s3://${{ secrets.AWS_S3_BUCKET_NAME }}/eftakhairul_islam_resume.pdf
